### ISSUE TITLE
devdev vs appdev directories?

### ISSUE THREAD

**Issue by bewest** [santoslab/aadl-translator#24]
In the plugin preferences, I noticed `devdev` vs `appdev` directories, and wondered what affect these might have.  I grepped through the source code and determined that `devdev` didn't seem to be used, but could not determine what effect if any `appdev` might have.

**Comment by sprocter** [comment]
The ```appdev``` directory is where the generated source code will be placed.  It's read in on [line 353 of DoTranslation.java](https://github.com/santoslab/aadl-translator/blob/master/aadl-translator/src/main/java/edu/ksu/cis/projects/mdcf/aadltranslator/DoTranslation.java#L353), and then that value is sent to the writer class.

I'm assigning Yu Jin to this in the hopes that he'll look into the use of the ```devdev``` directory.

**Comment by yjkim78** [comment]
Just like the app side, the devdev directory is the target location for the generated code on device.
Note that the feature related to the devdev settings are under development and it is has no effect on MDCF architect (http://santoslab.org/pub/mdcf-architect/).

**Comment by bewest** [comment]
Thanks, feel free to close, I see it's under development.  :-)

Thanks for all the goodies.  I managed to get going with the demo projects.

**Comment by yjkim78** [comment]
Thanks.
